# Site settings
title: "KITCTF"                 # TODO
description: "<!-- flag{596f755f6172655f617765736f6d655f3a29} -->"     # TODO
baseurl: ""
url: "http://ctf.saelo.net"                     # TODO

github: kitctf

# Build settings
markdown: kramdown
permalink: pretty

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo 

teamname: KITCTF
