# Site settings
title: "KITCTF"
baseurl: ""
url: "http://kitctf.de"

github: kitctf

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo

teamname: KITCTF
