# Site settings
title: "CTF (at) KIT (dot) edu"                 # TODO
description: "Yeah, we play CTF and stuff."     # TODO
baseurl: ""
url: "http://ctf.saelo.net"                     # TODO

github: kitctf

# Build settings
markdown: kramdown
permalink: pretty

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo 
