# Site settings
title: "KITCTF"
baseurl: ""
url: "http://kitctf.de"

github: kitctf
twitter: KITCTF

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo
  eboda:
    url: http://edgar-boda.com
  niklasb:
    url: https://github.com/niklasb

teamname: KITCTF
