# Site settings
title: "KITCTF"
description: "We play CTF and stuff..."
baseurl: ""
url: "http://kitctf.de"

github: kitctf

# Build settings
markdown: kramdown
permalink: pretty

# Authors
authors:
  saelo:
    url: https://twitter.com/5aelo
  eboda:
    url: http://edgar-boda.com

teamname: KITCTF
